version: '3'

services:
  web:
    build:
        context: ./get-started-service
        dockerfile: Dockerfile
    # command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./get-started-service:/usr/src/app
    ports:
      - 8000:8000
    # environment:
      # - ENVIRONMENT=dev
      # - TESTING=0
      # - DATABASE_URL=postgres://postgres:postgres@web-db:5432/web_dev
       # - DATABASE_URL=postgres://abc:abc123@localhost:5432/web_dev
      # - DATABASE_TEST_URL=postgres://postgres:postgres@web-db:5432/web_test

  #   depends_on:
  #     - web-db
  # web-db:
  #   build:
  #       context: ./get-started-service/db
  #       dockerfile: Dockerfile

    # expose:
    #     - 5432

    # environment:
    #     - POSTGRES_USER=abc
    #     - POSTGRES_PASSWORD=abc123
 